export const articlesData = [
  {
    id: 1,
    title: "Post Coronavirus World: Could We Expect a Better Domain?",
    publication: "International Journal of the Asian Philosophical Association",
    editor: "",
    publisher: "",
    publication_date: "July 2021",
    pages: "209-221",
    url: "",
    volume: "14",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 2,
    title: "Response to Civilizational Decline",
    publication: "Juan Cole Blog",
    editor: "",
    publisher: "",
    publication_date: "October 2023",
    pages: "",
    url: "https://www.juancole.com/2023/10/response-civilizational-decline.html",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 3,
    title: "Leaders Reacting to Conflict",
    publication: "Juan Cole Blog",
    editor: "",
    publisher: "",
    publication_date: "November 2023",
    pages: "",
    url: "https://www.juancole.com/2023/11/leaders-reacting-conflict.html",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 4,
    title:
      "Iqbal’s Visions of Civilization, Modernity and Nationalism: Are his Ideas Relevant Today?",
    publication: "Islamska Kultura U Tranziciji: Eseji u cast Fikreta Karcica",
    editor: "Ahmet Alibasic et.al.",
    publisher: "CNS",
    publication_date: "2020",
    pages: "77-100",
    url: "",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 5,
    title: "Consistent Dialogue of Civilizations",
    publication: "Juan Cole Blog",
    editor: "",
    publisher: "",
    publication_date: "2020",
    pages: "",
    url: "https://www.juancole.com/2020/07/consistent-dialogue-civilizations.html",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 6,
    title: "Coronavirus Xenophobia and Weak",
    publication: "Juan Cole Blog",
    editor: "",
    publisher: "",
    publication_date: "2020",
    pages: "",
    url: "https://www.juancole.com/2020/05/coronavirus-xenophobia-weak.html",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 7,
    title: "The OIC at Fifty: Between Hope and Despair",
    publication: "Al-Sharq Forum",
    editor: "",
    publisher: "",
    publication_date: "January 2019",
    pages: "",
    url: "https://www.sharqforum.org/2019/01/09/the-oic-at-fifty-between-hope-and-despair/",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 8,
    title: "The Question of Palestine and the Muslim World",
    publication: "New Middle Eastern Studies",
    editor: "",
    publisher: "",
    publication_date: "2018",
    pages: "84-106",
    url: "",
    volume: "8",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 9,
    title:
      "Is Pakistan a Failed State? An Assessment of Islamist Ideals, Nationalist Articulation and Ground Realities",
    publication: "Insight Turkey",
    editor: "",
    publisher: "",
    publication_date: "Winter 2018",
    pages: "119-141",
    url: "",
    volume: "20",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 10,
    title:
      "The Never-Ending Kashmir Dispute and Its Implications on the Contemporary Global Governance and Peace",
    publication: "Al-Shajarah",
    editor: "",
    publisher: "",
    publication_date: "2017",
    pages: "5-34",
    url: "",
    volume: "22",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 11,
    title: "What is History?",
    publication: "International Journal of Islamic Thoughts",
    editor: "",
    publisher: "",
    publication_date: "2016",
    pages: "17-32",
    url: "",
    volume: "5",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 12,
    title: "Islamization of Research in History",
    publication: "International Journal of Islamic Thoughts",
    editor: "",
    publisher: "",
    publication_date: "2015",
    pages: "43-62",
    url: "",
    volume: "4",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 13,
    title:
      "Civilisational Conflict, Renewal, or Transformation: Potential Role of the OIC",
    publication: "Islam and Civilisational Renewal",
    editor: "",
    publisher: "",
    publication_date: "October 2013",
    pages: "579-600",
    url: "",
    volume: "4",
    issue: "4",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 14,
    title:
      "Problems of Eurocentric Views of History: An Examination of Certain Elementary Views about Colonialism in the Muslim World",
    publication: "Al-Shajarah",
    editor: "",
    publisher: "",
    publication_date: "2013",
    pages: "35-58",
    url: "",
    volume: "18",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 15,
    title: "Dialogue of Civilizations: Islamic and Western Perceptions",
    publication: "Al-Shajarah",
    editor: "",
    publisher: "",
    publication_date: "2011",
    pages: "157-179",
    url: "",
    volume: "16",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 16,
    title:
      "The Rise of Turkey in the Arab-Muslim World: A Malaysian Perspective",
    publication: "Encompassing Crescent",
    editor: "",
    publisher: "",
    publication_date: "May 2011",
    pages: "",
    url: "",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 17,
    title:
      "Arab Spring or an Idealistic Dream? A Cursory Look at Uprisings in the Arab World",
    publication: "Pegasus Monthly Newsletter",
    editor: "",
    publisher: "",
    publication_date: "April 2011",
    pages: "8-9",
    url: "",
    volume: "1",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 18,
    title: "The Islamist Challenge: Between Modernization and Intimidation",
    publication: "Al-Shajarah",
    editor: "",
    publisher: "",
    publication_date: "2010",
    pages: "117-147",
    url: "",
    volume: "15",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 19,
    title:
      "The Clash of Civilizations Thesis and Muslims: The Search for an Alternative Paradigm",
    publication: "Islamic Studies",
    editor: "",
    publisher: "",
    publication_date: "2009",
    pages: "189-217",
    url: "",
    volume: "48",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 20,
    title:
      "Law, Religion and Human Dignity in the Muslim World Today: An Examination of OIC’s Cairo Declaration of Human Rights",
    publication: "Journal of Law and Religion",
    editor: "",
    publisher: "",
    publication_date: "2008-2009",
    pages: "569-597",
    url: "",
    volume: "24",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 21,
    title: "The Identity Crisis in the Muslim Ummah",
    publication: "Encompassing Crescent",
    editor: "",
    publisher: "",
    publication_date: "December 2008",
    pages: "4-6",
    url: "",
    volume: "2",
    issue: "4",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 22,
    title: "Muslim World at the Crossroads: The Role of the OIC",
    publication: "Journal of Islamic Studies",
    editor: "",
    publisher: "",
    publication_date: "2008",
    pages: "106-126",
    url: "",
    volume: "27",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 23,
    title:
      "From Conflict to Conversation: An Islamic View of Peaceful Coexistence of Civilizations",
    publication: "Islamic Studies",
    editor: "",
    publisher: "",
    publication_date: "2007",
    pages: "53-70",
    url: "",
    volume: "46",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 24,
    title: "Islamic State, Civilizational Dialogue and Southeast Asia",
    publication:
      "International Institute of Islamic Thought and Civilization (ISTAC)",
    editor: "",
    publisher: "",
    publication_date: "2007",
    pages: "71-96",
    url: "",
    volume: "6",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 25,
    title: "Islam Hadhari: A Revival of the Tradition of Islamic Universalism",
    publication: "Intellectual Discourse",
    editor: "",
    publisher: "",
    publication_date: "2006",
    pages: "55-68",
    url: "",
    volume: "14",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 26,
    title:
      "The OIC and the Western World: Drifting Towards Dialogue with Civilizations",
    publication: "American Journal of Islamic Social Sciences",
    editor: "",
    publisher: "",
    publication_date: "2005",
    pages: "1-15",
    url: "",
    volume: "22",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 27,
    title: "Contemporary Civilizational Crisis and the Role of the OIC",
    publication: "Journal of Muslim Minority Affairs",
    editor: "",
    publisher: "",
    publication_date: "2005",
    pages: "299-315",
    url: "",
    volume: "25",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 28,
    title:
      "Between Occident and Orient: The Role of International Islamic University Malaysia in Reviving the Intellectual Tradition of Islam",
    publication: "Intellectual Discourse",
    editor: "",
    publisher: "",
    publication_date: "2005",
    pages: "41-60",
    url: "",
    volume: "13",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 29,
    title: "Impact of the Muslim World on the West",
    publication: "Journal of Muslim Minority Affairs",
    editor: "",
    publisher: "",
    publication_date: "2004",
    pages: "299-312",
    url: "",
    volume: "24",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 30,
    title: "An Islamic Alternative? Perceptions of Muslim Intellectuals",
    publication: "Intellectual Discourse",
    editor: "",
    publisher: "",
    publication_date: "2003",
    pages: "75-88",
    url: "",
    volume: "11",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 31,
    title:
      "The Contribution of Asian Muslim States towards the Restructuring of the OIC",
    publication: "American Journal of Islamic Social Sciences",
    editor: "",
    publisher: "",
    publication_date: "2003",
    pages: "1-26",
    url: "",
    volume: "20",
    issue: "4",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 32,
    title: "The Organization of Islamic Conference and Human Rights",
    publication: "Insan ve Toplum",
    editor: "",
    publisher: "",
    publication_date: "2002",
    pages: "10-17",
    url: "",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 33,
    title: "An Islamic Concept of Human Rights",
    publication: "Intellectual Discourse",
    editor: "",
    publisher: "",
    publication_date: "2001",
    pages: "151-162",
    url: "",
    volume: "9",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 34,
    title: "Interstate Relations in Islam: An Islamic Framework of World Order",
    publication: "The American Journal of Islamic Social Sciences",
    editor: "",
    publisher: "",
    publication_date: "1992",
    pages: "19-42",
    url: "",
    volume: "9",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 35,
    title:
      "Islam and Violence: An Examination of Religious and Historical Perspectives",
    publication: "The American Journal of Islamic Social Sciences",
    editor: "",
    publisher: "",
    publication_date: "1990",
    pages: "245-257",
    url: "",
    volume: "7",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
  {
    id: 36,
    title: "Islam and the West: A Historical and Contemporary Perspective",
    publication: "International Journal of Islamic and Arabic Studies",
    editor: "",
    publisher: "",
    publication_date: "1989",
    pages: "11-22",
    url: "",
    volume: "6",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
  },
];
