export const articlesData = [
  {
    title: "The Question of Palestine and the Muslim World",
    publication: "New Middle Eastern Studies",
    editor: "",
    publisher: "",
    publication_date: "2018",
    pages: "84-106",
    url: "https://www.researchgate.net/publication/330527000_The_Question_of_Palestine_and_the_Muslim_World",
    volume: "8",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title:
      "Is Pakistan a Failed State? An Assessment of Islamist Ideals, Nationalist Articulation and Ground Realities",
    publication: "Insight Turkey",
    editor: "",
    publisher: "",
    publication_date: "Winter 2018",
    pages: "119-141",
    url: "https://www.insightturkey.com/articles/is-pakistan-a-failed-state-an-assessment-of-islamist-ideals-nationalist-articulation-and-ground-realities",
    volume: "20",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title:
      "The Never-Ending Kashmir Dispute and Its Implications on the Contemporary Global Governance and Peace",
    publication: "Al-Shajarah",
    editor: "",
    publisher: "",
    publication_date: "2017",
    pages: "5-34",
    url: "https://journals.iium.edu.my/shajarah/index.php/shaj/article/view/586",
    volume: "22",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title: "What is History?",
    publication: "International Journal of Islamic Thoughts",
    editor: "",
    publisher: "",
    publication_date: "2016",
    pages: "17-32",
    url: "https://journals.iium.edu.my/shajarah/index.php/shaj/article/view/295",
    volume: "5",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title: "Islamization of Research in History",
    publication: "International Journal of Islamic Thoughts",
    editor: "",
    publisher: "",
    publication_date: "2015",
    pages: "43-62",
    url: "https://journals.iium.edu.my/shajarah/index.php/shaj/article/view/18",
    volume: "4",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title:
      "Civilisational Conflict, Renewal, or Transformation: Potential Role of the OIC",
    publication: "Islam and Civilisational Renewal",
    editor: "",
    publisher: "",
    publication_date: "October 2013",
    pages: "579-600",
    url: "https://icrjournal.org/index.php/icr/article/view/439",
    volume: "4",
    issue: "4",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title:
      "Problems of Eurocentric Views of History: An Examination of Certain Elementary Views about Colonialism in the Muslim World",
    publication: "Al-Shajarah",
    editor: "",
    publisher: "",
    publication_date: "2013",
    pages: "35-58",
    url: "http://irep.iium.edu.my/32366",
    volume: "18",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title: "Dialogue of Civilizations: Islamic and Western Perceptions",
    publication: "Al-Shajarah",
    editor: "",
    publisher: "",
    publication_date: "2011",
    pages: "157-179",
    url: "",
    volume: "16",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title:
      "The Rise of Turkey in the Arab-Muslim World: A Malaysian Perspective",
    publication: "Encompassing Crescent",
    editor: "",
    publisher: "",
    publication_date: "May 2011",
    pages: "",
    url: "",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title:
      "Arab Spring or an Idealistic Dream? A Cursory Look at Uprisings in the Arab World",
    publication: "Pegasus Monthly Newsletter",
    editor: "",
    publisher: "",
    publication_date: "April 2011",
    pages: "8-9",
    url: "",
    volume: "1",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title: "The Islamist Challenge: Between Modernization and Intimidation",
    publication: "Al-Shajarah",
    editor: "",
    publisher: "",
    publication_date: "2010",
    pages: "117-147",
    url: "https://journals.iium.edu.my/shajarah/index.php/shaj/article/view/18",
    volume: "15",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title:
      "The Clash of Civilizations Thesis and Muslims: The Search for an Alternative Paradigm",
    publication: "Islamic Studies",
    editor: "",
    publisher: "",
    publication_date: "2009",
    pages: "189-217",
    url: "https://www.jstor.org/stable/20839161",
    volume: "48",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title:
      "Law, Religion and Human Dignity in the Muslim World Today: An Examination of OIC’s Cairo Declaration of Human Rights",
    publication: "Journal of Law and Religion",
    editor: "",
    publisher: "",
    publication_date: "2008-2009",
    pages: "569-597",
    url: "https://www.researchgate.net/publication/293198709_Law_Religion_and_Human_Dignity_in_the_Muslim_World_Today_An_Examination_of_OIC's_Cairo_Declaration_of_Human_Rights",
    volume: "24",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title: "Research Methodology in History",
    publication:
      "Toward Developing an Integrated Research Method in Human Sciences",
    editor: "Mohd. Yusof Hussain",
    publisher: "International Islamic University",
    publication_date: "2006",
    pages: "239-258",
    url: "",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title: "Political Discourse of the Organization of the Islamic Conference",
    publication: "The Blackwell Companion to Contemporary Islamic Thought",
    editor: "Ibrahim Abu Rabi",
    publisher: "Blackwell Publishing",
    publication_date: "2006",
    pages: "527-543",
    url: "https://onlinelibrary.wiley.com/doi/abs/10.1002/9780470996188.ch31",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title:
      "The Organization of the Islamic Conference: History, Function and Organization",
    publication: "Malaysia and the Islamic World",
    editor: "Abdul Razak Baginda",
    publisher: "ASEAN Academic Press",
    publication_date: "2004",
    pages: "31-68",
    url: "",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title:
      "Conflict among Muslim Nations: Role of the OIC in Conflict Resolution",
    publication: "Intellectual Discourse",
    editor: "",
    publisher: "",
    publication_date: "2004",
    pages: "137-157",
    url: "https://journals.iium.edu.my/intdiscourse/index.php/id/article/view/268",
    volume: "12",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title: "Pakistan since Independence",
    publication: "The Muslim World",
    editor: "",
    publisher: "",
    publication_date: "July-Oct. 2003",
    pages: "351-371",
    url: "https://www.researchgate.net/publication/229834572_Pakistan_since_Independence_An_Historical_Analysis",
    volume: "93",
    issue: "3-4",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title: "Muslim World and the United States: Friends or Foes?",
    publication: "Studies in Contemporary Islam",
    editor: "",
    publisher: "",
    publication_date: "2002",
    pages: "50-62",
    url: "https://digital.maag.ysu.edu:8443/xmlui/bitstream/handle/1989/7154/SCI4-2.pdf?sequence=2&isAllowed=y",
    volume: "4",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title: "On History, Progress and Civilization",
    publication: "AJISS",
    editor: "",
    publisher: "",
    publication_date: "Spring 2002",
    pages: "46-67",
    url: "https://www.ajis.org/index.php/ajiss/article/view/1970",
    volume: "19",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title:
      "Muslim and European Perceptions of Oceanic 'Trade' in the Fifteenth and Sixteenth Centuries and their Implications in International Politics",
    publication: "Intellectual Discourse",
    editor: "",
    publisher: "",
    publication_date: "1999",
    pages: "172-188",
    url: "",
    volume: "7",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title: "The Origin of Human History and the First Man",
    publication: "Islamic Studies",
    editor: "",
    publisher: "",
    publication_date: "Spring 1999",
    pages: "63-86",
    url: "",
    volume: "38",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title:
      "Elite Formation in Muslim Countries: Capable Administrators or Loyal Servants? A General Survey of Colonial Rule in Muslim Countries",
    publication: "Islamic Studies",
    editor: "",
    publisher: "",
    publication_date: "Spring 1998",
    pages: "29-55",
    url: "",
    volume: "37",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title: "Images Of Islam: Islamic Terrorism or Terrorizing the Truth?",
    publication: "Pakistan Journal of History and Culture",
    editor: "",
    publisher: "",
    publication_date: "1997",
    pages: "1-23",
    url: "",
    volume: "18",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title:
      "Organization of the Islamic Conference: An United Nations of Muslim Countries?",
    publication: "Iqbal Review",
    editor: "",
    publisher: "",
    publication_date: "Oct. 1997",
    pages: "13-27",
    url: "",
    volume: "38",
    issue: "3",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title:
      "Cooperation for Economic Development among Muslim Countries: The OIC Experience",
    publication: "IKIM Journal",
    editor: "",
    publisher: "",
    publication_date: "Jan-Jun 1997",
    pages: "19-34",
    url: "",
    volume: "5",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  {
    title: "The Spread of Islam in Pre-Mughal Bengal",
    publication: "Intellectual Discourse",
    editor: "",
    publisher: "",
    publication_date: "1994",
    pages: "41-55",
    url: "",
    volume: "2",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Academic",
  },
  // Op-eds start
  {
    title:
      "Is the One-Sided US Response to the Gaza Crisis a Sign of our Civilizational Decline?",
    publication: "Juan Cole Blog",
    editor: "",
    publisher: "",
    publication_date: "25 October 2023",
    pages: "",
    url: "https://www.juancole.com/2023/10/response-civilizational-decline.html",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
  {
    title: "How are leaders in the Muslim World reacting to the Gaza Conflict?",
    publication: "Juan Cole Blog",
    editor: "",
    publisher: "",
    publication_date: "11 November 2023",
    pages: "",
    url: "https://www.juancole.com/2023/11/leaders-reacting-conflict.html",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
  {
    title:
      "Rise of Hindutva ideology in India: An accident or a natural development?",
    publication: "Global Village Space",
    editor: "",
    publisher: "",
    publication_date: "14 February 2022",
    pages: "",
    url: "https://www.globalvillagespace.com/rise-of-hindutva-ideology-in-india-an-accident-or-natural-development",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
  {
    title:
      "Bangladesh was born amid Indo-Pak War in 1971 — But on 50th Anniversary, Who Owns that History?",
    publication: "Juan Cole Blog",
    editor: "",
    publisher: "",
    publication_date: "12 April 2021",
    pages: "",
    url: "https://www.juancole.com/2021/04/bangladesh-anniversary-history.html",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },

  {
    title: "Post Coronavirus World: Could We Expect a Better Domain?",
    publication: "International Journal of the Asian Philosophical Association",
    editor: "",
    publisher: "",
    publication_date: "July 2021",
    pages: "209-221",
    url: "",
    volume: "14",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
  {
    title:
      "The Coronavirus and Geo-Politics: Trump’s Xenophobia and Weapons of the Weak",
    publication: "Juan Cole Blog",
    editor: "",
    publisher: "",
    publication_date: "5 February 2020",
    pages: "",
    url: "https://www.juancole.com/2020/05/coronavirus-xenophobia-weak.html",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
  {
    title:
      "Turkey Turned the Hagia Sophia back into a Mosque: Is it Consistent with Muslim Values, the Dialogue of Civilizations?",
    publication: "Juan Cole Blog",
    editor: "",
    publisher: "",
    publication_date: "22 July 2020",
    pages: "",
    url: "https://www.juancole.com/2020/07/consistent-dialogue-civilizations.html",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
  {
    title:
      "Iqbal’s Visions of Civilization, Modernity and Nationalism: Are his Ideas Relevant Today?",
    publication: "Islamska Kultura U Tranziciji: Eseji u cast Fikreta Karcica",
    editor: "Ahmet Alibasic et.al.",
    publisher: "CNS",
    publication_date: "2020",
    pages: "77-100",
    url: "https://tehseel.com/index.php/tehseel/article/view/28",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },

  {
    title: "The OIC at Fifty: Between Hope and Despair",
    publication: "Al-Sharq Forum",
    editor: "",
    publisher: "",
    publication_date: "January 2019",
    pages: "",
    url: "",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
  {
    title: "What is History?",
    publication: "International Journal of Islamic Thoughts",
    editor: "",
    publisher: "",
    publication_date: "2016",
    pages: "17-32",
    url: "https://ijits.net/ojs3/index.php/ijits/article/view/70/69",
    volume: "5",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },

  {
    title: "The Identity Crisis in the Muslim Ummah",
    publication: "Encompassing Crescent",
    editor: "",
    publisher: "",
    publication_date: "December 2008",
    pages: "4-6",
    url: "https://www.ajis.org/index.php/ajiss/article/view/2478/1608",
    volume: "2",
    issue: "4",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },

  {
    title:
      "Civilizational Conflict? Looking at Islam and the West through the Prism of the OIC",
    publication: "Alternatives: Turkish Journal of International Relations",
    editor: "",
    publisher: "",
    publication_date: "Fall 2007",
    pages: "1-20",
    url: "",
    volume: "6",
    issue: "3&4",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
  {
    title:
      "September 11 and the Clash of Civilizations: An Islamic Perspective",
    publication: "Journal of Muslim Minority Affairs",
    editor: "",
    publisher: "",
    publication_date: "2006",
    pages: "219-232",
    url: "",
    volume: "26",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
  {
    title: "Islam and Modernity: A Malaysian Perspective",
    publication: "A Malay Civilisation: Islam and Modernity",
    editor: "A. Dr Mahathir Mohamad",
    publisher: "",
    publication_date: "2006",
    pages: "71-84",
    url: "",
    volume: "",
    issue: "",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
  {
    title: "Religious Pluralism: Secularism, Islam and Liberal Democracy",
    publication: "Journal of Muslim Minority Affairs",
    editor: "",
    publisher: "",
    publication_date: "2005",
    pages: "387-398",
    url: "",
    volume: "25",
    issue: "3",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },

  {
    title: "Islam, Ethnicity and Conflict in Malaysia",
    publication: "Journal of Muslim Minority Affairs",
    editor: "",
    publisher: "",
    publication_date: "2005",
    pages: "355-361",
    url: "",
    volume: "25",
    issue: "3",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
  {
    title: "Islamic Civilization in the 21st Century: The OIC’s Role",
    publication: "Islam and Civilisational Renewal",
    editor: "",
    publisher: "",
    publication_date: "2005",
    pages: "357-368",
    url: "",
    volume: "3",
    issue: "4",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
  {
    title: "Secularism and Its Discontents: The Malaysian Dilemma",
    publication: "Religion, State and Society",
    editor: "",
    publisher: "",
    publication_date: "2004",
    pages: "171-186",
    url: "",
    volume: "32",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
  {
    title: "Unity or Fragmentation? The OIC’s Role in the Muslim World",
    publication: "Journal of Diplomacy and Foreign Relations",
    editor: "",
    publisher: "",
    publication_date: "2003",
    pages: "19-29",
    url: "",
    volume: "5",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },

  {
    title: "The OIC and the Muslim World",
    publication: "Journal of Diplomacy and Foreign Relations",
    editor: "",
    publisher: "",
    publication_date: "2001",
    pages: "37-46",
    url: "",
    volume: "3",
    issue: "1",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
  {
    title: "Human Rights and the Muslim World",
    publication: "Journal of Diplomacy and Foreign Relations",
    editor: "",
    publisher: "",
    publication_date: "2001",
    pages: "59-69",
    url: "",
    volume: "3",
    issue: "2",
    doi: "",
    language: "English",
    abstract: "",
    keywords: [],
    category: "Op-eds",
  },
];
